# Generated by Django 2.2.6 on 2019-10-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_llamado', models.PositiveIntegerField(choices=[(1, 'convocatoria'), (2, 'inscripcion')])),
            ],
        ),
    ]
