# Generated by Django 2.2.6 on 2019-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamado',
            name='tipo_llamado',
            field=models.CharField(choices=[(1, 'convocatoria'), (2, 'inscripcion')], max_length=100),
        ),
    ]
