# Generated by Django 2.2.6 on 2019-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_auto_20191015_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamado',
            name='cargo',
            field=models.CharField(choices=[('ASISTENTE', 'Asistente'), ('AYUDANTE', 'Ayudante')], default='ASISTENTE', max_length=100),
        ),
        migrations.AddField(
            model_name='llamado',
            name='dedicacion',
            field=models.CharField(choices=[('EXCLUSIVA', 'Exclusiva'), ('SEMIEXCLUSIVA', 'Semiexclusiva'), ('SIMPLE', 'Simple')], default='SIMPLE', max_length=100),
        ),
        migrations.AddField(
            model_name='llamado',
            name='es_concurso_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llamado',
            name='es_revalida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='llamado',
            name='tipo_llamado',
            field=models.CharField(choices=[('CONVOCATORIA DE ASPIRANTES', 'Convocatoria de Aspirantes'), ('INSCRIPCION', 'Inscripcion')], max_length=100),
        ),
    ]
