# Generated by Django 2.2.6 on 2019-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0003_auto_20191015_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='llamado',
            name='asignaturas',
            field=models.ManyToManyField(to='concursos.Asignatura', verbose_name='Lista de Asignaturas'),
        ),
    ]
