# Generated by Django 2.2.6 on 2019-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0004_auto_20191015_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamado',
            name='fecha_apertura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='llamado',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
    ]
