# Generated by Django 2.2.6 on 2019-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0005_auto_20191015_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamado',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
