# Generated by Django 2.2.6 on 2019-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0006_llamado_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamado',
            old_name='asignaturas',
            new_name='asignatura',
        ),
        migrations.AlterField(
            model_name='llamado',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Publicar'),
        ),
    ]
