# Generated by Django 2.2.6 on 2019-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0007_auto_20191016_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamado',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llamado',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
